package com.renegarcia.tagphrgen;

import com.renegarcia.tagphrgen.swing.CheckBoxListRenderer;
import com.renegarcia.tagphrgen.swing.CheckboxListItem;
import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javazoom.jl.player.Player;



public class SwingGUI extends javax.swing.JFrame
{
    private TagalogPhraseGenerator generator;
    private static final Logger log = Logger.getLogger(SwingGUI.class.getName());
    private Sentence currentSentence;
    private InputStream currentAudioStream;
    private JList<CheckboxListItem> jlist;
    
    public SwingGUI() throws Exception
    {
        initComponents();
        setLocationRelativeTo(null);
        generator = new TagalogPhraseGenerator();
        
        initJList();
        
        
        
        nextAction();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        textLbl = new javax.swing.JLabel();
        scrollpane = new javax.swing.JScrollPane();
        selectAllBtn = new javax.swing.JButton();
        deselectAllBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        nextBtn = new javax.swing.JButton();
        playAudioBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tagalog Phrase Generator");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textLbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        textLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textLbl.setText("jLabel1");

        selectAllBtn.setText("Select All");
        selectAllBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                selectAllBtnActionPerformed(evt);
            }
        });

        deselectAllBtn.setText("Deselect All");
        deselectAllBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deselectAllBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollpane)
                    .addComponent(textLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(selectAllBtn)
                .addGap(18, 18, 18)
                .addComponent(deselectAllBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deselectAllBtn, selectAllBtn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectAllBtn)
                    .addComponent(deselectAllBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(textLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nextBtnActionPerformed(evt);
            }
        });

        playAudioBtn.setText("Play Audio");
        playAudioBtn.setEnabled(false);
        playAudioBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                playAudioBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(playAudioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {nextBtn, playAudioBtn});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextBtn)
                    .addComponent(playAudioBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void initJList() throws Exception
    {
        ArrayList<CheckboxListItem> list = new ArrayList<>();
        for(Sentence s: generator.getSentenceList())
            list.add(new CheckboxListItem(generator.makeSentenceFor(s, true)));
        
        CheckboxListItem[] arr = list.toArray(new CheckboxListItem[list.size()]);
        jlist = new JList<>(arr);
        jlist.setCellRenderer(new CheckBoxListRenderer());
        scrollpane.setViewportView(jlist);
        jlist.addMouseListener(new MouseAdapter()
        {
            @Override
            public void mouseClicked(MouseEvent event)
            {
                JList list = (JList) event.getSource();
                int index = list.locationToIndex(event.getPoint());// Get index of item
                // clicked
                CheckboxListItem item = (CheckboxListItem) list.getModel().getElementAt(index);
                item.setSelected(!item.isSelected()); // Toggle selected state
                list.repaint(list.getCellBounds(index, index));// Repaint cell
            }
        });
        
    }
    
    
    private void selectAll(boolean select)
    {
       int size = jlist.getModel().getSize();
       for(int i = 0; i < size; i++)
       {
           CheckboxListItem el = jlist.getModel().getElementAt(i);
           el.setSelected(select);
       }
       jlist.repaint();
    }
    
    
    private void nextAction() throws Exception
    {
        currentAudioStream = null;
        currentSentence = null; 
        playAudioBtn.setEnabled(false);
        
        //get random sentence from those selected in the jlist
        int size = jlist.getModel().getSize();
        ArrayList<Integer> list = new ArrayList<>();
        for(int i = 0; i < size; i++)
        {
            if(jlist.getModel().getElementAt(i).isSelected())
                list.add(i);
        }
        
        
        int idx = list.get(new Random().nextInt(list.size()));
        Sentence s = generator.getSentenceList().get( idx );
        
     
        currentSentence = generator.makeSentenceFor(s, true);
        textLbl.setText(currentSentence.english);
  
        
    
        new Thread(() ->
        {
            try
            {
                currentAudioStream = generator.textToAudio(currentSentence.tagalog);
                EventQueue.invokeLater(()-> {
                    playAudioBtn.setEnabled(true);
                });
            }
            catch (Exception ex)
            {
                
                log.log(Level.WARNING, null, ex);
            }
        }).start();
       
    }
    
    
    private void playAudioBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_playAudioBtnActionPerformed
    {//GEN-HEADEREND:event_playAudioBtnActionPerformed
       
        
        playAudioBtn.setEnabled(false);
        
        new Thread(() ->
        {       
            Player p;
            try
            {
                currentAudioStream.reset();
                p = new Player(currentAudioStream);
                p.play();
                p.close();
                
            }
            catch (Exception ex)
            {
                log.log(Level.WARNING, null, ex);
                
                EventQueue.invokeLater(()-> {
                     JOptionPane.showMessageDialog(this, "Unable to play audio.\n\n" + ex.getMessage(), "Audio Erro", JOptionPane.WARNING_MESSAGE);
                });
                
            }
            finally
            {
                EventQueue.invokeLater(() ->
                {
                    playAudioBtn.setEnabled(true);
                });
            }
            

        }).start();


        
     
          
           
           
            
       
       
    }//GEN-LAST:event_playAudioBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nextBtnActionPerformed
    {//GEN-HEADEREND:event_nextBtnActionPerformed
        try
        {
            nextAction();
        }
        catch (Exception ex)
        {
           log.log(Level.SEVERE, "Failed to generate sentence.", ex);
           JOptionPane.showMessageDialog(this, "Error", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void selectAllBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_selectAllBtnActionPerformed
    {//GEN-HEADEREND:event_selectAllBtnActionPerformed
        selectAll(true);
    }//GEN-LAST:event_selectAllBtnActionPerformed

    private void deselectAllBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deselectAllBtnActionPerformed
    {//GEN-HEADEREND:event_deselectAllBtnActionPerformed
        selectAll(false);
    }//GEN-LAST:event_deselectAllBtnActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deselectAllBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton playAudioBtn;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JButton selectAllBtn;
    private javax.swing.JLabel textLbl;
    // End of variables declaration//GEN-END:variables
}

